### ISSUE TITLE
Casting error?

### ISSUE THREAD

**Issue by Boyeen** [codewitch-honey-crisis/htcw_rmt_led_strip#1]
I can't compile the code because of (pardon my ignorance, I'm just a humble C programmer :-) casting errors? 
Can you "point" me in the right direction please ?

In member function 'virtual bool arduino::ws2812::initialize()':
.pio/libdeps/adafruit_feather_esp32s3/htcw_rmt_led_strip/src/rmt_led_strip.cpp:498:78: error: invalid conversion from 'void**' to 'uint32_t**' {aka 'unsigned int**'} [-fpermissive]

This occurs on other lines too, like 531, 636 etc.

**Comment by codewitch-honey-crisis** [comment]
I just published what i hope fixes it. It compiles now, but I don't have an led strip at the moment to test the fix. Thanks for bringing this to my attention, and feel free to reopen if there are any further problems.

**Comment by Boyeen** [comment]
Thank you so much. Yes, it compiles and more importantly works perfectly now.

The last time I opened an issue (another project) it took 6 months to get a reply/fix. I doubt I will ever get a 5 minute
response time again,  but I have one now to prove how amazing OSS  is.  

Thanks a million and Merry Christmas.

Tim
