### ISSUE TITLE
[FR] Project examples would be highly appreciated 

### ISSUE THREAD

**Issue by Slyfuchs** [codewitch-honey-crisis/htcw_rmt_led_strip#3]
Hi,

Currently, the [library page] https://github.com/codewitch-honey-crisis/htcw_rmt_led_strip doesn't contain any quick start code example. Also there is a short description on how to use, I somehow don't get it to compile and run.  

Please consider adding a comprehensive project example. 

Thanks in advance

**Comment by codewitch-honey-crisis** [comment]
https://github.com/codewitch-honey-crisis/iotetris/blob/main/include/neopixel_panel.hpp

**Comment by codewitch-honey-crisis** [comment]
added a small example
